name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn Pillow

      - name: Check Image Files
        run: |
          python -c "
          import os
          from PIL import Image
          
          # List all image extensions you want to check
          image_extensions = ['.jpg', '.jpeg', '.png', '.gif', '.bmp']
          
          # Find all image files in the repository
          image_files = []
          for root, _, files in os.walk('.'):
              for file in files:
                  if any(file.lower().endswith(ext) for ext in image_extensions):
                      image_files.append(os.path.join(root, file))
          
          print(f'Found {len(image_files)} image files to validate')
          
          # Try to open each image file
          failed_images = []
          for img_path in image_files:
              try:
                  with Image.open(img_path) as img:
                      img.verify()  # Verify image integrity
                  print(f'✓ Successfully loaded {img_path}')
              except Exception as e:
                  print(f'✗ Failed to load {img_path}: {e}')
                  failed_images.append(img_path)
          
          # Exit with error if any images failed
          if failed_images:
              print(f'ERROR: {len(failed_images)} images failed to load')
              exit(1)
          else:
              print('All images loaded successfully')
          "
